name: .NETMAUICI  

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET MAUI
      uses: dotnet/install-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore NuGet packages
      run: dotnet restore PincherApp.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore PincherApp.sln

    - name: Test
      run: dotnet test --configuration Release --no-build PincherApp/UnitTestProject/UnitTestProject.csproj

  manual-trigger:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET MAUI
      uses: dotnet/install-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore NuGet packages
      run: dotnet restore PincherApp.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore PincherApp.sln

    - name: Test
      run: dotnet test --configuration Release --no-build PincherApp/UnitTestProject/UnitTestProject.csproj
